# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/micko/Asiakirjat/Koodi/AstroStack.ui'
#
# Created: Wed Apr 16 21:24:10 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(783, 607)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(1, 23, 171, 541))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.pageFrames = QtGui.QWidget()
        self.pageFrames.setGeometry(QtCore.QRect(0, 0, 161, 375))
        self.pageFrames.setObjectName(_fromUtf8("pageFrames"))
        self.label_6 = QtGui.QLabel(self.pageFrames)
        self.label_6.setGeometry(QtCore.QRect(7, 0, 61, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(self.pageFrames)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 20, 101, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayoutFrameAdd = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayoutFrameAdd.setMargin(0)
        self.verticalLayoutFrameAdd.setObjectName(_fromUtf8("verticalLayoutFrameAdd"))
        self.pushLight = QtGui.QPushButton(self.layoutWidget)
        self.pushLight.setObjectName(_fromUtf8("pushLight"))
        self.verticalLayoutFrameAdd.addWidget(self.pushLight)
        self.pushDark = QtGui.QPushButton(self.layoutWidget)
        self.pushDark.setObjectName(_fromUtf8("pushDark"))
        self.verticalLayoutFrameAdd.addWidget(self.pushDark)
        self.pushBias = QtGui.QPushButton(self.layoutWidget)
        self.pushBias.setObjectName(_fromUtf8("pushBias"))
        self.verticalLayoutFrameAdd.addWidget(self.pushBias)
        self.pushFlat = QtGui.QPushButton(self.layoutWidget)
        self.pushFlat.setObjectName(_fromUtf8("pushFlat"))
        self.verticalLayoutFrameAdd.addWidget(self.pushFlat)
        self.toolBox.addItem(self.pageFrames, _fromUtf8(""))
        self.pageCalib = QtGui.QWidget()
        self.pageCalib.setGeometry(QtCore.QRect(0, 0, 161, 375))
        self.pageCalib.setObjectName(_fromUtf8("pageCalib"))
        self.layoutWidget1 = QtGui.QWidget(self.pageCalib)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 141, 241))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayoutCalibrate = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayoutCalibrate.setMargin(0)
        self.verticalLayoutCalibrate.setObjectName(_fromUtf8("verticalLayoutCalibrate"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayoutCalibrate.addWidget(self.label_3)
        self.checkBoxDarkBias = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxDarkBias.setObjectName(_fromUtf8("checkBoxDarkBias"))
        self.verticalLayoutCalibrate.addWidget(self.checkBoxDarkBias)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayoutCalibrate.addWidget(self.label_4)
        self.checkBoxFlatBias = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxFlatBias.setObjectName(_fromUtf8("checkBoxFlatBias"))
        self.verticalLayoutCalibrate.addWidget(self.checkBoxFlatBias)
        self.checkBoxFlatDark = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxFlatDark.setObjectName(_fromUtf8("checkBoxFlatDark"))
        self.verticalLayoutCalibrate.addWidget(self.checkBoxFlatDark)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayoutCalibrate.addWidget(self.label_5)
        self.checkBoxLightBias = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxLightBias.setObjectName(_fromUtf8("checkBoxLightBias"))
        self.verticalLayoutCalibrate.addWidget(self.checkBoxLightBias)
        self.checkBoxLightDark = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxLightDark.setObjectName(_fromUtf8("checkBoxLightDark"))
        self.verticalLayoutCalibrate.addWidget(self.checkBoxLightDark)
        self.checkBoxLightFlat = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxLightFlat.setObjectName(_fromUtf8("checkBoxLightFlat"))
        self.verticalLayoutCalibrate.addWidget(self.checkBoxLightFlat)
        self.toolBox.addItem(self.pageCalib, _fromUtf8(""))
        self.pageDebayer = QtGui.QWidget()
        self.pageDebayer.setGeometry(QtCore.QRect(0, 0, 161, 375))
        self.pageDebayer.setObjectName(_fromUtf8("pageDebayer"))
        self.layoutWidget2 = QtGui.QWidget(self.pageDebayer)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 161, 111))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayoutDebayer = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayoutDebayer.setMargin(0)
        self.verticalLayoutDebayer.setObjectName(_fromUtf8("verticalLayoutDebayer"))
        self.radioButtonBilinearCyt = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonBilinearCyt.setObjectName(_fromUtf8("radioButtonBilinearCyt"))
        self.buttonDebayer = QtGui.QButtonGroup(MainWindow)
        self.buttonDebayer.setObjectName(_fromUtf8("buttonDebayer"))
        self.buttonDebayer.addButton(self.radioButtonBilinearCyt)
        self.verticalLayoutDebayer.addWidget(self.radioButtonBilinearCyt)
        self.radioButtonVNGCyt = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonVNGCyt.setObjectName(_fromUtf8("radioButtonVNGCyt"))
        self.buttonDebayer.addButton(self.radioButtonVNGCyt)
        self.verticalLayoutDebayer.addWidget(self.radioButtonVNGCyt)
        self.radioButtonBilinearCL = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonBilinearCL.setObjectName(_fromUtf8("radioButtonBilinearCL"))
        self.buttonDebayer.addButton(self.radioButtonBilinearCL)
        self.verticalLayoutDebayer.addWidget(self.radioButtonBilinearCL)
        self.radioButtonVNGCL = QtGui.QRadioButton(self.layoutWidget2)
        self.radioButtonVNGCL.setObjectName(_fromUtf8("radioButtonVNGCL"))
        self.buttonDebayer.addButton(self.radioButtonVNGCL)
        self.verticalLayoutDebayer.addWidget(self.radioButtonVNGCL)
        self.toolBox.addItem(self.pageDebayer, _fromUtf8(""))
        self.pageReg = QtGui.QWidget()
        self.pageReg.setGeometry(QtCore.QRect(0, 0, 161, 375))
        self.pageReg.setObjectName(_fromUtf8("pageReg"))
        self.layoutWidget3 = QtGui.QWidget(self.pageReg)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 10, 161, 73))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayoutRegister = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayoutRegister.setMargin(0)
        self.verticalLayoutRegister.setObjectName(_fromUtf8("verticalLayoutRegister"))
        self.radioButtonGrothIM = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonGrothIM.setObjectName(_fromUtf8("radioButtonGrothIM"))
        self.buttonRegister = QtGui.QButtonGroup(MainWindow)
        self.buttonRegister.setObjectName(_fromUtf8("buttonRegister"))
        self.buttonRegister.addButton(self.radioButtonGrothIM)
        self.verticalLayoutRegister.addWidget(self.radioButtonGrothIM)
        self.radioButtonGrothSK = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonGrothSK.setObjectName(_fromUtf8("radioButtonGrothSK"))
        self.buttonRegister.addButton(self.radioButtonGrothSK)
        self.verticalLayoutRegister.addWidget(self.radioButtonGrothSK)
        self.radioButtonLegacy = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonLegacy.setObjectName(_fromUtf8("radioButtonLegacy"))
        self.buttonRegister.addButton(self.radioButtonLegacy)
        self.verticalLayoutRegister.addWidget(self.radioButtonLegacy)
        self.toolBox.addItem(self.pageReg, _fromUtf8(""))
        self.pageStack = QtGui.QWidget()
        self.pageStack.setGeometry(QtCore.QRect(0, 0, 161, 375))
        self.pageStack.setObjectName(_fromUtf8("pageStack"))
        self.layoutWidget4 = QtGui.QWidget(self.pageStack)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 111, 48))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayoutStack = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayoutStack.setMargin(0)
        self.verticalLayoutStack.setObjectName(_fromUtf8("verticalLayoutStack"))
        self.radioButtonMean = QtGui.QRadioButton(self.layoutWidget4)
        self.radioButtonMean.setObjectName(_fromUtf8("radioButtonMean"))
        self.buttonStack = QtGui.QButtonGroup(MainWindow)
        self.buttonStack.setObjectName(_fromUtf8("buttonStack"))
        self.buttonStack.addButton(self.radioButtonMean)
        self.verticalLayoutStack.addWidget(self.radioButtonMean)
        self.radioButtonMedian = QtGui.QRadioButton(self.layoutWidget4)
        self.radioButtonMedian.setObjectName(_fromUtf8("radioButtonMedian"))
        self.buttonStack.addButton(self.radioButtonMedian)
        self.verticalLayoutStack.addWidget(self.radioButtonMedian)
        self.toolBox.addItem(self.pageStack, _fromUtf8(""))
        self.pageRun = QtGui.QWidget()
        self.pageRun.setGeometry(QtCore.QRect(0, 0, 161, 375))
        self.pageRun.setObjectName(_fromUtf8("pageRun"))
        self.label_2 = QtGui.QLabel(self.pageRun)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButtonRun = QtGui.QPushButton(self.pageRun)
        self.pushButtonRun.setGeometry(QtCore.QRect(10, 160, 151, 23))
        self.pushButtonRun.setObjectName(_fromUtf8("pushButtonRun"))
        self.layoutWidget5 = QtGui.QWidget(self.pageRun)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 20, 161, 123))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayoutRun = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayoutRun.setMargin(0)
        self.verticalLayoutRun.setObjectName(_fromUtf8("verticalLayoutRun"))
        self.checkBoxCalib = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxCalib.setObjectName(_fromUtf8("checkBoxCalib"))
        self.verticalLayoutRun.addWidget(self.checkBoxCalib)
        self.checkBoxDebayer = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxDebayer.setObjectName(_fromUtf8("checkBoxDebayer"))
        self.verticalLayoutRun.addWidget(self.checkBoxDebayer)
        self.checkBoxReg = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxReg.setObjectName(_fromUtf8("checkBoxReg"))
        self.verticalLayoutRun.addWidget(self.checkBoxReg)
        self.checkBoxStack = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxStack.setObjectName(_fromUtf8("checkBoxStack"))
        self.verticalLayoutRun.addWidget(self.checkBoxStack)
        self.toolBox.addItem(self.pageRun, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(180, 20, 601, 541))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_project = QtGui.QAction(MainWindow)
        self.actionOpen_project.setObjectName(_fromUtf8("actionOpen_project"))
        self.actionSave_project = QtGui.QAction(MainWindow)
        self.actionSave_project.setObjectName(_fromUtf8("actionSave_project"))
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addAction(self.actionOpen_project)
        self.menuFile.addAction(self.actionSave_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "Add", None))
        self.pushLight.setText(_translate("MainWindow", "Light", None))
        self.pushDark.setText(_translate("MainWindow", "Dark", None))
        self.pushBias.setText(_translate("MainWindow", "Bias", None))
        self.pushFlat.setText(_translate("MainWindow", "Flat", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFrames), _translate("MainWindow", "Frames", None))
        self.label_3.setText(_translate("MainWindow", "Dark frames", None))
        self.checkBoxDarkBias.setText(_translate("MainWindow", "Subtract bias", None))
        self.label_4.setText(_translate("MainWindow", "Flat frames", None))
        self.checkBoxFlatBias.setText(_translate("MainWindow", "Subtract bias", None))
        self.checkBoxFlatDark.setText(_translate("MainWindow", "Subtract dark", None))
        self.label_5.setText(_translate("MainWindow", "Light frames", None))
        self.checkBoxLightBias.setText(_translate("MainWindow", "Subtract bias", None))
        self.checkBoxLightDark.setText(_translate("MainWindow", "Subtract dark", None))
        self.checkBoxLightFlat.setText(_translate("MainWindow", "Divide by flat", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageCalib), _translate("MainWindow", "Calibrating", None))
        self.radioButtonBilinearCyt.setText(_translate("MainWindow", "Bilinear Cython", None))
        self.radioButtonVNGCyt.setText(_translate("MainWindow", "VNG Cython", None))
        self.radioButtonBilinearCL.setText(_translate("MainWindow", "Bilinear OpenCL", None))
        self.radioButtonVNGCL.setText(_translate("MainWindow", "VNG OpenCL", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageDebayer), _translate("MainWindow", "Debayering", None))
        self.radioButtonGrothIM.setText(_translate("MainWindow", "Groth + ImageMagick", None))
        self.radioButtonGrothSK.setText(_translate("MainWindow", "Groth + Scikit", None))
        self.radioButtonLegacy.setText(_translate("MainWindow", "Legacy", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageReg), _translate("MainWindow", "Registering", None))
        self.radioButtonMean.setText(_translate("MainWindow", "Mean", None))
        self.radioButtonMedian.setText(_translate("MainWindow", "Median", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageStack), _translate("MainWindow", "Stacking", None))
        self.label_2.setText(_translate("MainWindow", "Set workflow", None))
        self.pushButtonRun.setText(_translate("MainWindow", "Run", None))
        self.checkBoxCalib.setText(_translate("MainWindow", "Calibrate", None))
        self.checkBoxDebayer.setText(_translate("MainWindow", "Debayer", None))
        self.checkBoxReg.setText(_translate("MainWindow", "Register", None))
        self.checkBoxStack.setText(_translate("MainWindow", "Stack", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageRun), _translate("MainWindow", "Run", None))
        self.label.setText(_translate("MainWindow", "Project settings", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project", None))
        self.actionSave_project.setText(_translate("MainWindow", "Save project", None))
        self.actionNew_project.setText(_translate("MainWindow", "New project", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

