#!/usr/bin/python3
# -'''- coding: utf-8 -'''-

import sys
from mosstack import NewGui
from PySide.QtCore import *
from PySide.QtGui import *
from PySide.QtDeclarative import QDeclarativeView

if __name__ == "__main__":

    GUI = NewGui.GUI(sys.argv)
    sys.exit(GUI.app.exec_())