#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Created on 28.10.2013

@author: Mikko Laine

Main program for pyAstroStack.

This command line user interface is used to create a project file to store information
about source files and temporary files in working directory. This same UI is then used
to run different stacking operations according to the project file.
"""

import sys
from astrostack import Config, Debayer, Registering, Stacker
import os
from astrostack.UserInterface import UserInterface
#import cProfile


def main(argv):
    """
    The idea is to call program with
    mosstack projectname operation arguments
    """

    ui = UserInterface()

    #setup = Config.Setup()

    shorthelp = ui.shorthelp

    longhelp = ui.longhelp
    project  = None
    section  = None
    calib    = None

    if len(argv) == 0:
        print(shorthelp)
        exit()

    if argv[0] == "init":
        project = Config.Project()
        project.initproject(argv[1])
        Config.Global.set("Default", "Project", argv[1])

    try:
        pname = Config.Global.get("Default", "Project")
        ppath = Config.Global.get("Default", "Path") + pname + ".project"
        if argv[0] == "set" and argv[1] == "project":
            pass
        else:
            print("Current project is " + ppath + "\n")
        project = Config.Project(pname)
        project.readproject()
        ui.setproject(project)

    except IndexError:
        print("Something went wrong. Check your input. Refer to \"mosstack help\" if needed.")
        exit()

    if argv[0] == "help":
        print(longhelp)

    if argv[0] == "init":
        exit()

    elif argv[0] == "set":

        if argv[1] == "project":
            if argv[2]:
                pname = argv[2]
                Config.Global.set("Default", "Project", pname)
                ppath = Config.Global.get("Default", "Path") + pname + ".project"
                project = Config.Project(pname)
                print("Project set to " + ppath)
            else:
                print("No project name specified. Available projects are: Implement this")
                print("Try mosstack set project <project name>, without extension.")
        elif argv[1] == "debayer":
            options = Debayer.__all__
            ui.set("Debayer", options, argv[2])
        elif argv[1] == "register":
            options = Registering.__all__
            ui.set("Register", options, argv[2])
        elif argv[1] == "stack":
            options = Stacker.__all__
            ui.set("Stack", options, argv[2])

        else:
            print("Don't know how to set " + argv[1])
            print("Possible options to set are \n project\n Debayer\n register\n stack")

    elif argv[0] == "list":

        if len(argv) == 1:
            print("Settings to list are \n debayer\n register\n stack")
        else:
            if argv[1] == "debayer":
                options = Debayer.__all__
            elif argv[1] == "register":
                options = Registering.__all__
            elif argv[1] == "stack":
                options = Stacker.__all__
            else:
                print("No such setting " + argv[1])
                print("Possible settings are \n debayer\n register\n stack")
                exit()
            ui.list(argv[1], options)

    elif argv[0] == "dir":

        if argv[1]:
            directory = argv[1]
        else:
            directory = os.getcwd()

        itype = argv[2]
        ui.adddir(directory, itype)
        #project.adddir(directory, itype)

    elif argv[0] == "file":

        itype = argv[2]
        project.addfile(argv[1], itype)

    elif argv[0] == "stack":
        # AstroStack stack <srcname>
        srclist = ("light", "dark", "bias", "flat", "rgb", "calib", "reg")
        if argv[1] in srclist:
            section = argv[1]
        else:
            print("Invalid argument: " + argv[1])
            print("<itype> has to be one of: " + str(srclist))

        ui.stack(section)

    elif argv[0] == "debayer":
        # AstroStack debayer <srcname>

        if argv[1]:
            fphase = argv[1]

        else:
            print("Scrname not defined. Try 'mosstack debayer calib' or 'mosstack debayer light'\nExiting...")
            exit()

        ui.debayer(fphase)

    elif argv[0] == "register":
        # AstroStack register <srcname>

        if argv[1]:
            fphase = argv[1]
        else:
            print("Srcname not defined. Exiting...")
            exit()

        ui.register(fphase)

    elif argv[0] == "subtract":
        # AstroStack subtract <srcname> <calibname>

        if argv[1]:
            section = argv[1]
            if argv[2]:
                calib = argv[2]
            else:
                print("Calibname not defined. Exiting...")
                exit()
        else:
            print("Srcname not defined. Exiting...")
            exit()

        ui.subtract(section, calib)

    elif argv[0] == "divide":
        # AstroStack divide <srcname> <calibname>

        if argv[1]:
            section = argv[1]
            if argv[2]:
                calib = argv[2]
            else:
                print("Calibname not defined. Exiting...")
                exit()
        else:
            print("Srcname not defined. Exiting...")
            exit()

        ui.divide(section, calib)

    else:
        print("Invalid operation: " + argv[0])
        print(shorthelp)
        exit()

if __name__ == "__main__":
    main(sys.argv[1:])