#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Created on 2015

@author: Mikko Laine

Main program for mosstack.

This command line user interface is used to create a project file to store information
about source files and temporary files in working directory. This same UI is then used
to run different stacking operations according to the project file.
"""

import sys
from mosstack.CommandLine import CommandLine


def main(argv):
    """
    Call user interface with requested arguments.
    """

    ui = CommandLine()

    ui.start(argv)

    #ui.print_values()

if __name__ == "__main__":
    main(sys.argv[1:])
